package tokenizer

/*Mnemonic represents strings that are also valid Mnemonics in the RISC-V 32-I Assembly Language*/
type Mnemonic string

/*These string constants represent the valid RiscV Assembly Mnemonics for instructions*/
const (
	ADDI       Mnemonic = "ADDI"
	SLTI       Mnemonic = "SLTI"
	SLTIU      Mnemonic = "SLTIU"
	ANDI       Mnemonic = "ANDI"
	ORI        Mnemonic = "ORI"
	XORI       Mnemonic = "XORI"
	SLLI       Mnemonic = "SLLI"
	SRLI       Mnemonic = "SRLI"
	SRAI       Mnemonic = "SRAI"
	LUI        Mnemonic = "LUI"
	AUIPC      Mnemonic = "AUIPC"
	ADD        Mnemonic = "ADD"
	SLT        Mnemonic = "SLT"
	SLTU       Mnemonic = "SLTU"
	AND        Mnemonic = "AND"
	OR         Mnemonic = "OR"
	XOR        Mnemonic = "XOR"
	SLL        Mnemonic = "SLL"
	SRL        Mnemonic = "SRL"
	SUB        Mnemonic = "SUB"
	SRA        Mnemonic = "SRA"
	NOP        Mnemonic = "NOP"
	JAL        Mnemonic = "JAL"
	JALR       Mnemonic = "JALR"
	BEQ        Mnemonic = "BEQ"
	BNE        Mnemonic = "BNE"
	BLT        Mnemonic = "BLT"
	BLTU       Mnemonic = "BLTU"
	BGE        Mnemonic = "BGE"
	BGEU       Mnemonic = "BGEU"
	LW         Mnemonic = "LW"
	LH         Mnemonic = "LH"
	LHU        Mnemonic = "LHU"
	LB         Mnemonic = "LB"
	LBU        Mnemonic = "LBU"
	SW         Mnemonic = "SW"
	SH         Mnemonic = "SH"
	SB         Mnemonic = "SB"
	CSRRW      Mnemonic = "CSRRW"
	CSRRS      Mnemonic = "CSRRS"
	CSRRC      Mnemonic = "CSRRC"
	CSRRWI     Mnemonic = "CSRRWI"
	CSRRSI     Mnemonic = "CSRRSI"
	CSRRCI     Mnemonic = "CSRRCI"
	CSRR       Mnemonic = "CSRR"
	CSRW       Mnemonic = "CSRW"
	CSRWI      Mnemonic = "CSRWI"
	CSRS       Mnemonic = "CSRS"
	CSRSI      Mnemonic = "CSRSI"
	CSRC       Mnemonic = "CSRC"
	CSRCI      Mnemonic = "CSRCI"
	ECALL      Mnemonic = "ECALL"
	EBREAK     Mnemonic = "EBREAK"
	MV         Mnemonic = "MV"
	SEQZ       Mnemonic = "SEQZ"
	NOT        Mnemonic = "NOT"
	SNEZ       Mnemonic = "SNEZ"
	J          Mnemonic = "J"
	RDCYCLE    Mnemonic = "RDCYCLE"
	RDCYCLEH   Mnemonic = "RDCYCLEH"
	RDTIME     Mnemonic = "RDTIME"
	RDTIMEH    Mnemonic = "RDTIMEH"
	RDINSTRET  Mnemonic = "RDINSTRET"
	RDINSTRETH Mnemonic = "RDINSTRETH"
	BGT        Mnemonic = "BGT"
	BGTU       Mnemonic = "BGTU"
	BLE        Mnemonic = "BLE"
	BLEU       Mnemonic = "BLEU"
)

/*Register represents strings that are valid Registers*/
type Register string

/*These string constants represent valid registers in RISC-V 32I Assembly Language*/
const (
	X0  Register = "x0"
	X1  Register = "x1"
	X2  Register = "x2"
	X3  Register = "x3"
	X4  Register = "x4"
	X5  Register = "x5"
	X6  Register = "x6"
	X7  Register = "x7"
	X8  Register = "x8"
	X9  Register = "x9"
	X10 Register = "x10"
	X11 Register = "x11"
	X12 Register = "x12"
	X13 Register = "x13"
	X14 Register = "x14"
	X15 Register = "x15"
	X16 Register = "x16"
	X17 Register = "x17"
	X18 Register = "x18"
	X19 Register = "x19"
	X20 Register = "x20"
	X21 Register = "x21"
	X22 Register = "x22"
	X23 Register = "x23"
	X24 Register = "x24"
	X25 Register = "x25"
	X26 Register = "x26"
	X27 Register = "x27"
	X28 Register = "x28"
	X29 Register = "x29"
	X30 Register = "x30"
	X31 Register = "x31"
)

/*RegisterNickname represents strings that are valid Register Nicknames*/
type RegisterNickname string

/*These string constants represent valid register nicknames in the RISC-V 32I Assembly Language*/
const (
	Zero          RegisterNickname = "zero"
	ReturnAddress RegisterNickname = "ra"
	StackPointer  RegisterNickname = "sp"
	GlobalPointer RegisterNickname = "gp"
	ThreadPointer RegisterNickname = "tp"
	Temp0         RegisterNickname = "t0"
	Temp1         RegisterNickname = "t1"
	Temp2         RegisterNickname = "t2"
	Saved0        RegisterNickname = "s0"
	FramePointer  RegisterNickname = "fp"
	Saved1        RegisterNickname = "s1"
	ArgRet0       RegisterNickname = "a0"
	ArgRet1       RegisterNickname = "a1"
	Arg2          RegisterNickname = "a2"
	Arg3          RegisterNickname = "a3"
	Arg4          RegisterNickname = "a4"
	Arg5          RegisterNickname = "a5"
	Arg6          RegisterNickname = "a6"
	Arg7          RegisterNickname = "a7"
	Saved2        RegisterNickname = "s2"
	Saved3        RegisterNickname = "s3"
	Saved4        RegisterNickname = "s4"
	Saved5        RegisterNickname = "s5"
	Saved6        RegisterNickname = "s6"
	Saved7        RegisterNickname = "s7"
	Saved8        RegisterNickname = "s8"
	Saved9        RegisterNickname = "s9"
	Saved10       RegisterNickname = "s10"
	Saved11       RegisterNickname = "s11"
	Temp3         RegisterNickname = "t3"
	Temp4         RegisterNickname = "t4"
	Temp5         RegisterNickname = "t5"
	Temp6         RegisterNickname = "t6"
)
