package tokenizer

/*Mnemonic represents strings that are also valid Mnemonics in the RISC-V 32-I Assembly Language*/
type Mnemonic string

/*These string constants represent the valid RiscV Assembly Mnemonics for instructions*/
const (
	ADDI       Mnemonic = "ADDI"
	SLTI       Mnemonic = "SLTI"
	SLTIU      Mnemonic = "SLTIU"
	ANDI       Mnemonic = "ANDI"
	ORI        Mnemonic = "ORI"
	XORI       Mnemonic = "XORI"
	SLLI       Mnemonic = "SLLI"
	SRLI       Mnemonic = "SRLI"
	SRAI       Mnemonic = "SRAI"
	LUI        Mnemonic = "LUI"
	AUIPC      Mnemonic = "AUIPC"
	ADD        Mnemonic = "ADD"
	SLT        Mnemonic = "SLT"
	SLTU       Mnemonic = "SLTU"
	AND        Mnemonic = "AND"
	OR         Mnemonic = "OR"
	XOR        Mnemonic = "XOR"
	SLL        Mnemonic = "SLL"
	SRL        Mnemonic = "SRL"
	SUB        Mnemonic = "SUB"
	SRA        Mnemonic = "SRA"
	NOP        Mnemonic = "NOP"
	JAL        Mnemonic = "JAL"
	JALR       Mnemonic = "JALR"
	BEQ        Mnemonic = "BEQ"
	BNE        Mnemonic = "BNE"
	BLT        Mnemonic = "BLT"
	BLTU       Mnemonic = "BLTU"
	BGE        Mnemonic = "BGE"
	BGEU       Mnemonic = "BGEU"
	LW         Mnemonic = "LW"
	LH         Mnemonic = "LH"
	LHU        Mnemonic = "LHU"
	LB         Mnemonic = "LB"
	LBU        Mnemonic = "LBU"
	SW         Mnemonic = "SW"
	SH         Mnemonic = "SH"
	SB         Mnemonic = "SB"
	CSRRW      Mnemonic = "CSRRW"
	CSRRS      Mnemonic = "CSRRS"
	CSRRC      Mnemonic = "CSRRC"
	CSRRWI     Mnemonic = "CSRRWI"
	CSRRSI     Mnemonic = "CSRRSI"
	CSRRCI     Mnemonic = "CSRRCI"
	CSRR       Mnemonic = "CSRR"
	CSRW       Mnemonic = "CSRW"
	CSRWI      Mnemonic = "CSRWI"
	CSRS       Mnemonic = "CSRS"
	CSRSI      Mnemonic = "CSRSI"
	CSRC       Mnemonic = "CSRC"
	CSRCI      Mnemonic = "CSRCI"
	ECALL      Mnemonic = "ECALL"
	EBREAK     Mnemonic = "EBREAK"
	MV         Mnemonic = "MV"
	SEQZ       Mnemonic = "SEQZ"
	NOT        Mnemonic = "NOT"
	SNEZ       Mnemonic = "SNEZ"
	J          Mnemonic = "J"
	RDCYCLE    Mnemonic = "RDCYCLE"
	RDCYCLEH   Mnemonic = "RDCYCLEH"
	RDTIME     Mnemonic = "RDTIME"
	RDTIMEH    Mnemonic = "RDTIMEH"
	RDINSTRET  Mnemonic = "RDINSTRET"
	RDINSTRETH Mnemonic = "RDINSTRETH"
	BGT        Mnemonic = "BGT"
	BGTU       Mnemonic = "BGTU"
	BLE        Mnemonic = "BLE"
	BLEU       Mnemonic = "BLEU"
)

/*Register represents strings that are valid Registers*/
type Register string

/*These string constants represent valid registers in RISC-V 32I Assembly Language*/
const (
	X0  = "x0"
	X1  = "x1"
	X2  = "x2"
	X3  = "x3"
	X4  = "x4"
	X5  = "x5"
	X6  = "x6"
	X7  = "x7"
	X8  = "x8"
	X9  = "x9"
	X10 = "x10"
	X11 = "x11"
	X12 = "x12"
	X13 = "x13"
	X14 = "x14"
	X15 = "x15"
	X16 = "x16"
	X17 = "x17"
	X18 = "x18"
	X19 = "x19"
	X20 = "x20"
	X21 = "x21"
	X22 = "x22"
	X23 = "x23"
	X24 = "x24"
	X25 = "x25"
	X26 = "x26"
	X27 = "x27"
	X28 = "x28"
	X29 = "x29"
	X30 = "x30"
	X31 = "x31"
)
